name: Sync to personal repo
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Push to personal repo
        env:
          TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        run: |
          git config --global user.email "sync@ethos.app"
          git config --global user.name "Sync Bot"
          git remote set-url origin https://ethossustainability:${TOKEN}@github.com/ethossustainability/ethosdashboard.git
          git push origin HEAD:main --force
